[package]
name = "replance"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "rnc"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
rustyline = { version = "15.0.0", features = ["with-file-history"] }
serde_json = "1.0.140"
